ren xx01 appendfile.cmd
ren xx02 appendtofile.cmd
ren xx03 appendnumbparam.cmd
ren xx04 autoit.cmd
ren xx05 calc.cmd
ren xx06 calcnumbparam.cmd
ren xx07 cct.cmd
ren xx08 ccta.cmd
ren xx09 checkdir.cmd
ren xx10 command.cmd
ren xx11 command2file.cmd
ren xx12 command2var.cmd
ren xx13 copy.cmd
ren xx14 file.cmd
ren xx15 copy2usb.cmd
ren xx16 date.cmd
ren xx17 dec.cmd
ren xx18 delfile.cmd
ren xx19 detectdateformat.cmd
ren xx20 drivepath.cmd
ren xx21 dummy.cmd
ren xx22 echo.cmd
ren xx23 encoding.cmd
ren xx24 fatal.cmd
ren xx25 fb.cmd
ren xx26 funcbegin.cmd
ren xx27 funcendtest.cmd
ren xx28 funcend.cmd
ren xx29 iconv.cmd
ren xx30 ifequal.cmd
ren xx31 ifnotequal.cmd
ren xx32 ifexist.cmd
ren xx33 ifnotexist.cmd
ren xx34 inc.cmd
ren xx35 exit-prompt.cmd
ren xx36 inccount.cmd
ren xx37 infile.cmd
ren xx38 ini2xslt.cmd
ren xx39 rexxini.cmd
ren xx40 iniline2var.cmd
ren xx41 iniparse4xslt.cmd
ren xx42 inisection.cmd
ren xx43 inputfile.cmd
ren xx44 jade.cmd
ren xx45 javahometest.cmd
ren xx46 javainpathtest.cmd
ren xx47 javanotfound.cmd
ren xx48 last.cmd
ren xx49 loopfolders.cmd
ren xx50 loopfiles.cmd
ren xx51 looplist.cmd
ren xx52 loopnumber.cmd
ren xx53 loopstring.cmd
ren xx54 mergevar.cmd
ren xx55 modelcheck.cmd
ren xx56 name.cmd
ren xx57 nameext.cmd
ren xx58 outfile.cmd
ren xx59 outputfile.cmd
ren xx60 paratextio.cmd
ren xx61 pause.cmd
ren xx62 perl.cmd
ren xx63 prince.cmd
ren xx64 ptbook.cmd
ren xx65 ptbkno.cmd
ren xx66 regex.cmd
ren xx67 rho.cmd
ren xx68 scriptfind.cmd
ren xx69 setinfolevel.cmd
ren xx70 setup.cmd
ren xx71 setup-batch.cmd
ren xx72 unicodecount.cmd
ren xx73 uniqcount.cmd
ren xx74 start.cmd
ren xx75 starturl.cmd
ren xx76 taskgroup.cmd
ren xx77 test.cmd
ren xx78 tidy.cmd
ren xx79 time.cmd
ren xx80 unittest.cmd
ren xx81 unittestaccumulate.cmd
ren xx82 var.cmd
